### PR TITLE
SearchingBox enchancements

### LINKED ISSUE #9: SearchingBox Ignore Case option
An option to ignore case of the searched option would be nice.

For settings like that:
image
This is the current behaviour:
image

### LINKED ISSUE #10: SearchingBox display Group of found Setting
An option to display a group that the Setting belongs to would be nice.

For a scene:
image

This is the current behaviour:
image

### PR DESCRIPTION
**Pull request by LightTab2**
Fixes #9 and fixes #10. Also changes name of `titleBar` to `SearchBar` (sorry for conflicts! I think `TextureRect` should be renamed to `SearchIcon`, but I won't make more potentially conflicting changes), adds top margin to `SettingsPanel` and Left, Right margins to `SearchBar`, so it can be adjusted easier. Also small restyling of the `SearchBox`.

For settings like this:
image

Search can display `Groups` (disabled by default) and has a `Partial Open` state:
Godot_v4 3-stable_win64_VoabHjx2aX

Search can ignore case (enabled by default):
Godot_v4 3-stable_win64_NClQpRpZzD

Closed groups matched by search will be in 'Partial Open' state even if display `Groups` is off:
Godot_v4 3-stable_win64_V30QrrnTYq

### CODE REVIEW

**Comment by LightTab2** [comment]
There is still issue that if displaying `Groups` is turned off, certain searches can display unintuitive results like this:
Godot_v4 3-stable_win64_w73GvvbGos
Here one might think, the _Ui Scale_ `Setting` belongs to _Gameplay_, but it doesn't. It was simply matched by search. I cannot fix it, because there is no fix, but a design choice must be made (simpliest is calling this desired behaviour or making `Display Groups` always on)

**Comment by albinaask** [comment]
Thank you for the issue and solution to one of the issues. I've created a new issue for the issue where the group buttons disappear. This should of course not be the case. The changing of the names aren't necessarily a problem since they are only meant to be internal, and not part of the SEAL API, this means that a minor version bump is warranted however, which I'll fix when I update of the add-on with all your fixes to the godot market place!

**Comment by LightTab2** [comment]
>  I've created a new issue for the issue where the group buttons disappear. This should of course not be the case. 

I probably didn't describe well enough what "Displaying `Groups`" is ^^.
I didn't know what was the intended behaviour at the time so I created this exported variable `_search_box_display_groups` which I call _Displaying `Groups`_ option, which translates roughly to:
**Everytime a search is matched, also display its parent `Group`.**

If you say this is the intended behaviour, then simply making `Display Groups` always on (removing the variable at all) will fix #15.

But I am not sure if this is what everybody wants and if for example adding a separator line per `Group` when search is on is better (that would be the behaviour when `_search_box_display_groups` is set to `false`).



_Also, a personal sidenote, you seem overly grateful for little I did, when those are simply fixes that I need for my current project. No need to thank for every piece of code as I believe most of us don't do this for glory or thanks. The whole open source community is about sharing things we hope other people will find useful. We should be most grateful for your share as it is the biggest one and whole initiative for improving Settings management in Godot (another great open source project) :)_

**Comment by albinaask** [comment]
Well, the idea is that you should be able to either search for a group, aka a search for "i" should display the entire "Interface" group(including the collapsible header button), and then also any setting that contains the letter "i" in it's name.

Regarding the thanking. Yes, I definitely acknowledge my part. The trend I see is that for example of the Godot survey that only like 5% of the users (i think I remember) have ever supported the project by either providing code, opening issues or just adding the wiki. Let alone the statistics of helping other are in my view abysmal. I sincerely think that for a proper open source eco system to work, we as the participants have to do better than that and saying thank you is a very easy milestone to that end.

I also think you underestimate your own value. Fixing bugs and keeping a software updated in line with user's expectation above a functional standard takes a lot of work, so in not having to divert my energy to maintenance and split my focus really reduces the toll on my time and energy. This means that my next (rather awsome if I say so myself) project may come just a little closer.

**Comment by LightTab2** [comment]
I have encountered something troublesome.

In the testing scene we can see a group that is split into two and searching for the group name seems almost fine (for some reason Key Option is being omitted):
Godot_v4 3-stable_win64_y6OuT84vrL

But if I search for individual options, weird things happen - the settings are under wrong group, or to be more precise, under no group at all (as the group above is certainly closed):
Godot_v4 3-stable_win64_X68mzK8i4b

I'd like to open a new issue, but is it issue with sorting or searching?

Should the group be split like that at all? I don't know what is the bug and what is intended.

**Comment by LightTab2** [comment]
Fixes #15 now:
image
Groups are always displayed if any of the `Settings` is matched.

`Partial Open` state remains unchanged (when not all `Settings` are matched **or** the `Group` is closed, but open temporarily due to the search):
Godot_v4 3-stable_win64_dFam7A5U0F

**Comment by LightTab2** [comment]
Fixes #16.

**Comment by albinaask** [comment]
This is a splendid plan. And good work. However, the PR doesn't pass the res://tests/steeingstesting.tscn test case. (You'll have to comment out the "load_from_GSON()" on line 31 in res://addons/SEAL/Demo/GlobalSettings.gd" to make the test work, my bad). It seem to reference 'group_button.was_last_state_closed' in 'SettingsPainter'. What does this code?

**Comment by LightTab2** [comment]
`was_last_state_closed` is a kind of memory for the new *Partial Open* state. When the search is cleared it tells if the *Group Header* should be closed now (because it was closed before and was only open because it matched the search) or open now (because it entered *Partial Open* state due to not all Settings being matched by the search). 

Also, not as important, the memory is needed to determine if it needs to remain in *Partial Open*, because it **can't check now if icon is equal to closed/open icon**, cuz its *partial open icon* now! Without it, the button would 'flicker' between open/closed and partially open everytime search is updated (and still valid), which actually happened due to my oversight and it looked funny :)

While I'll be looking at the test's fail reason, I would like to fix the issue I mentioned above with sorting/searching. Should it be allowed for a *Group* to be **split** like that and we'd fix it by adding 'another' Group Header above *Settings* that are split or should we **move** them so they are under one *Group Header* or maybe do both and make it an exported boolean variable to switch the behaviour? I kinda don't see the use case for the former option, so maybe just the latter (move *Settings*)? 

My time is being limited beceause of university but I will look into it with some delay if that's okay.

**Comment by albinaask** [comment]
Some delay is no problem on my part. Not at all. Take your time. 

Regarding the splitting: The idea with the test in this regard is to make sure that groups spelled almost the same are still different. The misspell is there in the code, so the groups aren't as much split as they are completely independent from the start. So unless I misinterpret you I cannot see a bug in this regard. Or have I misunderstood your meaning?

Also, I pushed all the other changes as well as I fixed the bug with GlobalSettings to a new version and uploaded it to the asset store. I'll make another version when this PR is done!

**Comment by LightTab2** [comment]
Ah yes, indeed the crouch KeySetting belongs to **gorup 2** not **group 2**, so there is no bug with not displaying but there is with splitting.

Maybe I didn't explain what splitting is clearly.
Godot_v4 3-stable_win64_X68mzK8i4b

In this test case, we first add **setting 3**, **setting 2** to the **group 2**. Then we create settings for **float and vectors groups** and then we add **color** and **multi choice** settings to **group 2 AGAIN**. This causes the bug as shown above and I described it more thoroughly 6 comments above.

I see there is still some room for misunderstanding, so maybe we should disscuss it over Discord:lighttab2?

**Comment by albinaask** [comment]
I added you!

**Comment by LightTab2** [comment]
I resolved the conflicts and fixed `was_last_state_closed` error. I think this PR can be merged and the splitting issue is tied to sorting not search, so I'll create a dedicated branch to it, for better documentation.

**Pull request merged**
